// importing mongoose
const mongoose = require("mongoose");

// defining Payment schema
// this schema represents a payment transaction made by a user for purchasing a plan
const paymentSchema = new mongoose.Schema(
    {
        // user field stores the ObjectId of the user who made the payment
        //reference syntax : {type : mongoose.Schema.Types.ObjectId, ref : "ReferencedModelName"}   
        //it stores the unique identifier of the user, e.g., "user": "64f8c12a9e5c2a..."
        // it references the User model to establish a relationship between payment and user
        // required: true ensures that every payment is associated with a user
        user : { type : mongoose.Schema.Types.ObjectId, ref:"User", required : true },

        // plan field stores the ObjectId of the plan that the user is paying for
        // it references the Plan model to identify which subscription or service plan was purchased
        // required: true ensures that a payment is always linked to a valid plan   
        plan : { type : mongoose.Schema.Types.ObjectId, ref :"Plan", required : true},

        // amount field stores the total amount paid by the user
        // type is Number and required because payment amount must always be specified
        amount : {type : Number, required : true},

        // currency field stores the currency used for the payment
        // default is set to "INR" assuming payments are primarily in Indian Rupees
        // this allows future support for multiple currencies if needed
        currency : {type : String, default : "INR"},

        // receipt field stores a unique receipt identifier generated for the payment
        // required: true ensures every payment has a receipt for tracking and reference
        receipt : { type : String, required : true},

        // razorpayOrderId stores the order ID generated by Razorpay when the payment is created
        // required: true ensures every payment has an associated Razorpay order
        // index: true improves query performance when searching payments by order ID
        razorpayOrderId : {type : String, required:true, index : true},

        // razorpayPaymentId stores the payment ID returned by Razorpay after successful payment
        // default: null because this value is not available until the payment is completed
        razorpayPaymentId : {type : String, default : null},

        // status field represents the current state of the payment
        // enum restricts the value to "created", "paid", or "failed"
        // default is "created" when the payment is initially generated
        status : {type : String, enum : ["created", "paid", "failed"], default : "created"}
    },
    {
        // timestamps option automatically adds createdAt and updatedAt fields
        // createdAt stores when the payment record was created
        // updatedAt stores when the payment record was last updated
        timestamp:true
    }
)

// creating the Payment model using the paymentSchema
// "Payment" is the model name and MongoDB will create a collection named "payments"
const Payment = mongoose.model("Payment",paymentSchema);
export default Payment;